name: 'Build'

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm install
      - run: pnpm db:generate
      - run: pnpm build
