name: 'Watcher Cronjob'
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  cron:
    name: 'Watcher Cronjob'
    runs-on: bkk
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm install
      - run: pnpm db:generate
      - run: pnpm build --filter=watcher
      - run: cd apps/watcher && pnpm start
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
