name: 'Pull Request Check'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm install
      - run: pnpm db:generate
      - run: pnpm lint
      - run: pnpm build
