name: 'Build and Run (BKK)'
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: 'Build and Run'
    runs-on: bkk
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: node apps/watcher/dist/index.js
